

INCLUDE = -I../../hdr
CXX = g++
CPPFLAGS = -g -Wall $(INCLUDE)






SRC = context.cpp halfExp.cpp listEndExp.cpp startExp.cpp 
OBJ = context.o halfExp.o listEndExp.o startExp.o 

TARGET : $(OBJ)


.cpp.o:
	$(CXX) $(CPPFLAGS)  $<



